import {
  menuCoffeeTraditional,
  menuCoffeeAmerican,
  menuCoffeeCreamy,
  menuCoffeeIced,
  menuCoffeeWithMilk,
  menuLatte,
  menuCapuccino,
  menuMocchiato,
  menuMocaccino,
  menuHotChocolate,
  menuCoffeeCubano,
  menuCoffeeHavaiano,
  menuCoffeeArabe,
  menuCoffeeIrlandes,
} from '../../assets'

export const coffeesData = [
  {
    id: '001',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    tags: ['Tradicional'],
    image: menuCoffeeTraditional,
    price: 9.9,
  },
  {
    id: '002',
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    tags: ['Tradicional'],
    image: menuCoffeeAmerican,
    price: 9.9,
  },
  {
    id: '003',
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    tags: ['Tradicional'],
    image: menuCoffeeCreamy,
    price: 9.9,
  },
  {
    id: '004',
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    tags: ['Tradicional', 'Gelado'],
    image: menuCoffeeIced,
    price: 9.9,
  },
  {
    id: '005',
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    tags: ['Tradicional', 'Com leite'],
    image: menuCoffeeWithMilk,
    price: 9.9,
  },
  {
    id: '006',
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    tags: ['Tradicional', 'Com leite'],
    image: menuLatte,
    price: 9.9,
  },
  {
    id: '007',
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    tags: ['Tradicional', 'Com leite'],
    image: menuCapuccino,
    price: 9.9,
  },
  {
    id: '008',
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    tags: ['Tradicional', 'Com leite'],
    image: menuMocchiato,
    price: 9.9,
  },
  {
    id: '009',
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    tags: ['Tradicional', 'Com leite'],
    image: menuMocaccino,
    price: 9.9,
  },
  {
    id: '010',
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    tags: ['Especial', 'Com leite'],
    image: menuHotChocolate,
    price: 9.9,
  },
  {
    id: '011',
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    tags: ['Especial', 'Alcoólico', 'Gelado'],
    image: menuCoffeeCubano,
    price: 9.9,
  },
  {
    id: '012',
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    tags: ['Especial'],
    image: menuCoffeeHavaiano,
    price: 9.9,
  },
  {
    id: '013',
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    tags: ['Especial'],
    image: menuCoffeeArabe,
    price: 9.9,
  },
  {
    id: '014',
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    tags: ['Especial', 'Alcoólico'],
    image: menuCoffeeIrlandes,
    price: 9.9,
  },
]
